### PR TITLE
Allow Easdif static build

### PR DESCRIPTION
**Pull request by gillesdegottex**

### CODE REVIEW

**Comment by roebel** [comment]
Hi Gilles 

I don't quite see what you want to do here. For me and with the version in the current branch

cmake ../ -DEASDIF_BUILD_STATIC:BOOL=1

configures the project in the to byld static and dynamic libraries alreadyThen I do 

make

and this results in 

ls lib/
libEasdif.1.4.26.dylib	libEasdif.dylib		libEasdif_static.a	libEasdif_static_pic.a	libsdif.3.11.6.dylib	libsdif.dylib

static libraries are present. Note that sdif sources need to be compiled with C++ compiler to be useful for Easdif and that's why the easdif library always includes all sdif objects, that the case here with libEasdif_static.a that contains all sdif sources copiled with the Easdif settings (see below).

So in fact i think the project is fine as it is and does all is needed for your static library.

please explain if you see any issues that I may have missed.

best
Axel

ar -t lib/libEasdif_static.a
__.SYMDEF
sdifentity.cpp.o
sdifexception.cpp.o
sdif_matrix.cpp.o
sdif_frame.cpp.o
sdifnamevaluetable.cpp.o
sdifinit.cpp.o
SdifCheck.cxx.o
SdifConvToText.cxx.o
SdifErrMess.cxx.o
SdifFGet.cxx.o
SdifFile.cxx.o
SdifFPrint.cxx.o
SdifFPut.cxx.o
SdifFrame.cxx.o
SdifFrameType.cxx.o
SdifFRead.cxx.o
SdifFScan.cxx.o
SdifFWrite.cxx.o
SdifGlobals.cxx.o
SdifHard_OS.cxx.o
SdifHash.cxx.o
SdifHighLevel.cxx.o
SdifList.cxx.o
SdifMatrix.cxx.o
SdifMatrixType.cxx.o
SdifNameValue.cxx.o
SdifPreTypes.cxx.o
SdifPrint.cxx.o
SdifRWLowLevel.cxx.o
SdifSelect.cxx.o
SdifSignatureTab.cxx.o
SdifStreamID.cxx.o
SdifString.cxx.o
SdifTest.cxx.o
SdifTextConv.cxx.o
SdifTimePosition.cxx.o

**Comment by gillesdegottex** [comment]
Apologies, I did this at least a year ago and I didn't look at the diff properly. The title is missleading.

This patch installs the static libs alongside the dynamic ones in INSTALL_LIB_DIR.

**Comment by gillesdegottex** [comment]
Indeed, it worked without this fix in my repo (??) I can't remember what I had fixed.
I close this PR and deleted my fork.

**Comment by gillesdegottex** [comment]
Found the reason of this patch at last:
The problem is that headers and dynamic libs are installed in the install directory, but the static libs stays in the compilation directory.
This means that when you want to use the static lib, you have to point your header path to the installation directory and the lib path to the compilation directory, which is not very convenient (there is not a single library root path for compiling with easdif in static).

Why not install the static libs alongside the dynamic ones? (@roebel )

**Pull request closed without merging**
